---
name: End to end pipeline that builds the image, tests it locally, remotely and deploys it

on:
  workflow_dispatch: # Only run manually

jobs:
  build:
    uses: ./.github/workflows/end-to-end-1-build.yml

  test-in-ci:
    uses: ./.github/workflows/end-to-end-2-test-in-ci.yml
    needs: build

  test-in-spcs:
    uses: ./.github/workflows/end-to-end-3-test-in-spcs.yml
    needs: build
    secrets: inherit

  deploy-to-spcs-prod:
    needs: test-spcs
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 1
