---
name: "[Pipeline] Build docker archive"

on:
  workflow_call:
  workflow_dispatch: # Allows running this workflow manually

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: spcs-ci-cd

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build --platform linux/amd64 -t $IMAGE_TAG:latest .
          docker save $IMAGE_TAG:latest -o ./out

      # Upload artifact to github cache
      - uses: actions/upload-artifact@v4
        with:
          path: ./out


