---
name: "[Pipeline] End to end"

on:
  workflow_dispatch: # Only run manually

jobs:
  # Builds the container image
  build:
    uses: ./.github/workflows/end-to-end-1-build.yml

  # Runs the container image in docker and runs the unit tests
  test-in-ci:
    uses: ./.github/workflows/end-to-end-2-test-in-ci.yml
    needs: build

  # Deploys a test service in SPCS, runs integration tests
  test-in-spcs:
    uses: ./.github/workflows/end-to-end-3-test-in-spcs.yml
    needs: build
    secrets: inherit

  # Deploys the service into production
  deploy-to-spcs-prod:
    needs: [test-in-spcs, test-in-ci]
    uses: ./.github/workflows/end-to-end-4-deploy-to-prod.yml
