---
name: "[Pipeline] Run tests against docker container running locally"

on:
  workflow_call:
  workflow_dispatch:


jobs:
  run-local-hurl-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Using nix to take better advantage of caching than apt-get update & friends
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |-
              experimental-features = pipe-operators nix-command flakes

      # Set up cache to cache build-related things
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # Download artifact from the build step
      - uses: actions/download-artifact@v4

      # Start detached docker process
      - name: Run docker image in container
        run: utils/docker-run

      # Run the tests on the docker image running on the same machine
      - name: Run tests
        run: |
          nix develop .#default --command "test-local-hurl"

