---
name: "[Pipeline] Build docker archive"

on:
  workflow_call:
  workflow_dispatch: # Allows running this workflow manually

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: spcs-ci-cd

    steps:
      - uses: actions/checkout@v4

      # Using nix to take better advantage of caching than apt-get update & friends
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |-
              experimental-features = pipe-operators nix-command flakes

      # NOTE: magic-nix-cache stopped working on Feb 1, 2025
      # Issue:
      # https://github.com/DeterminateSystems/magic-nix-cache/issues/123
      #
      # # Set up cache to cache build-related things
      # - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build image (produce docker archive file)
        run: |
          nix build -o out .#default


      # Upload artifact to github cache
      - uses: actions/upload-artifact@v4
        with:
          path: ./out


