---
name: Build and push container image using kaniko

# yamllint disable-line rule:truthy
on:
  workflow_dispatch: # Only run manually

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/work/key.p8
      IMAGE_TAG: spcs-ci-cd


    steps:
      - name: Mask repo-related values in Github logs
        # REGISTRY_URL can be retrieved by DESC IMAGE REPOSITORY <PATH>
        run: |
          IFS='/' read -ra URL_PARTS <<< "${{ secrets.REGISTRY_URL }}"
          for i in "${URL_PARTS[@]}"; do
             echo "::add-mask::$i"
          done

      - uses: actions/checkout@v4

      - uses: Snowflake-Labs/snowflake-cli-action@main
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      - name: Set up key
        run: |
          cat <<EOF > ${{ env.SNOWFLAKE_PRIVATE_KEY_PATH }}
          ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          EOF

      - name: Generate the token
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          SNOW_SPCS_LOGIN=$(snow spcs image-registry token --format=JSON)

          # WARN: Make sure to mask the token in the logs
          echo "::add-mask::$(echo $SNOW_SPCS_LOGIN | jq ".token")"

          {
            echo 'SPCS_TOKEN<<EOF'
            echo "$SNOW_SPCS_LOGIN"
            echo EOF
          } >> "$GITHUB_ENV"


      - name: Remove key
        run: |
          rm -f ${{ env.SNOWFLAKE_PRIVATE_KEY_PATH }}

      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: 0sessiontoken
          password: ${{ env.SPCS_TOKEN }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          executor: "gcr.io/kaniko-project/executor:v1.23.0-debug"
          tags: ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_TAG }}-kaniko:${{ github.sha }}
